import sys
import time
def slowprint(str): 
    for letter in str: 
        sys.stdout.write(letter) 
        sys.stdout.flush() 
        time.sleep(0.2)
def slowfastprint(str): 
    for letter in str: 
        sys.stdout.write(letter) 
        sys.stdout.flush() 
        time.sleep(0.12)
slowfastprint("restarting program . . .")
time.sleep(1)
slowprint("Enter name ")
name = (input( ))
slowprint("enter password")
password1 = (input( ))
while name == password1:
    print("password can not be the same as your name. Please try again.")
    password1 = (input( ))
slowprint("Loading " + str (name)+ "'s encrypted files.")
time.sleep(1)
print("please insert hint to remember the password")
hint = (input( ))
while password1 == hint or name == hint:
    print("hint can not be the same as the password or username. Please try again.")
    hint = (input())
time.sleep(1)
print("Program has restarted")
time.sleep(1)
slowprint(". . .")
time.sleep(0.5)
slowprint("logging on. ")
time.sleep(0.5)
print("Hello Elon Musk")
print("Loading")
time.sleep(1)
slowfastprint(". . .")
time.sleep(0.5)
slowprint(str(name) + " is waking up")

print("**Memory Flash**")
time.sleep(1)
def sprint(str): 
    for letter in str: 
        sys.stdout.write(letter) 
        sys.stdout.flush() 
        time.sleep(0.05)
sprint("Mom come on, the movie is about to begin.")
time.sleep(1)
sprint("Mom: okay sweetie I am coming")
sprint("While the movie fades in, the crowd hushes, and their anticipation rises as a deep voice starts:")
sprint("As the world devours by a newly discovered poison, creating humans into savages and eliminating their species.")
sprint("A new era begins through SpaceX’s mission to live on Mars and escape the spreading of the poison as it is incurable.")
sprint("Special appreciation to Elon Musk, his untested spaceship, worked saving billions of lives by evacuating to Mars.")
sprint("Unfortunately, we will always cherish in our hearts the souls that we lost and…")
time.sleep(3)


print("**Memory Flash**")
time.sleep(1)
def light(str): 
    for letter in str: 
        sys.stdout.write(letter) 
        sys.stdout.flush() 
        time.sleep(0.09)
light("Scientists have been operating a way back to Earth safely.")
time.sleep(3)
light("They are predicting only a couple more years to start to investigate the survivors who acquired the poison.")
time.sleep(4)
light("They say that it is very likely for humanity to live back on Earth...")
time.sleep(3)
       
print("**Memory Flash**")
time.sleep(1)
def lightspeed(str): 
    for letter in str: 
        sys.stdout.write(letter) 
        sys.stdout.flush() 
        time.sleep(0.009)
lightspeed("Security: go back to my room.")
time.sleep(2)
lightspeed("What do you remember doing?")
time.sleep(2)
escaping = int(input("1= getting through the guard by force 2= listening to the guard"))
if escaping == 1:
    lightspeed("I went through the guard forcefully as I wanted to see what is happening outside")
    time.sleep(4)
    lightspeed("and everything suddenly slowed down as I saw my mom go up in front of billions of people")
    time.sleep(4)
    
elif escaping == 2:
    lightspeed("I listened to the guard ")
    time.sleep(2)
    lightspeed("then I had a marvellous idea to open the T.V. and went on ABC news to observe what is happening outside,")
    time.sleep(4)
    lightspeed("and everything suddenly slowed down as I saw my mom go up in front of billions of people")
    time.sleep(4)

else:
    lightspeed("I do not remember doing anything else but wanting to see what is happening outside, so I went through the guard forcefully.")
    time.sleep(4)
    lightspeed("and everything suddenly slowed down as I saw my mom go up in front of billions of people")
    time.sleep(4)

lightspeed("My mother commenced with what looked like the most displeasing speech of her life.")
time.sleep(5)
lightspeed("mom: Sadly, there has been an unfavourable term of events we have been working extremely hard on going back to Earth.")
time.sleep(5)
lightspeed("However, we cannot know if it is survivable as there is no connection to our services that are on Earth...")
time.sleep(5)
lightspeed("There is only one way we can reach contact with Earth's services, and that is sending someone down there.")
time.sleep(5)
lightspeed("*the crowd gets loud and anger, and my mom tries to speak up*")
time.sleep(4)
lightspeed("It is too risky to assign any of our essential workers to go to Earth as we need them here to help us, ")
time.sleep(5)
lightspeed("so we will have to send someone from the crowd to assist us on our mission.")
time.sleep(4)

print("**Memory Flash**")

lightspeed("I looked around, and all I saw was grumpy people pushing a shoving each other and yelling: ")
time.sleep(5)
lightspeed("'There must be another way'")
time.sleep(2)
lightspeed("'My daughter died because you left on Earth to die'")
time.sleep(3)
lightspeed("'There is no way I am going down there for you, to only leave me to die as well'")
time.sleep(4)

print("**Memory Flash**")

lightspeed("Mom: 'I have made my decision, I understand the circumstance that we are all in,")
time.sleep(5)
lightspeed("and I cannot just ask for someone to offer their life for a chance for humanity to live.")
time.sleep(5)
lightspeed("So I have concluded that I will be sending my son to the ground.'")
time.sleep(4)
lightspeed("My heart sank to the ground.")
time.sleep(3)
lightspeed("'no... no … no … NOOOOOOOO!'")
time.sleep(2)
lightspeed("This can’t be happening.")
time.sleep(3)

print("**Memory Flash**")

lightspeed("I hear my mom crying in the background, and Elon Musk is trying to comfort her. ")
time.sleep(5)
lightspeed("Elon Musk: 'I know this is hard, do not worry he will be in safe hands, he is going to be fine.'")
time.sleep(5)

print("**Memory Flash**")

lightspeed("Elon Musk: 'Remove his memories we do not need any interferences to our objective and inject the microchip at the back of his head.'")
time.sleep(6)

print("**Flash**")

print("I opened my eyes slowly, hurting and terrified. Everything came slowly to vision.")
time.sleep(5)
print("'Whe… Wher… where am I? Who are you and What am I doing here?'")
time.sleep(5)
print("Stranger: 'NONONO, calm down I just finished brain surgery on you.")
time.sleep(5)
print("Do not worry you're fine. I will explain everything.'")
time.sleep(5)
print("'Good'")
time.sleep(5)
print("Stranger: 'as soon as I get some answers first.'")
time.sleep(5)
print("'what answers, I don't even know what is going on to answer you.'")
time.sleep(5)
print("Stranger: 'ya right, so you are not some undercover agent that is trying to spy on me?'")
time.sleep(5)
print("*twitch*'no'")
time.sleep(5)
print("Stranger: 'kill me?'")
time.sleep(5)
print("'No!'*twitch*")
time.sleep(5)
print("Stranger: 'imprison me?'")
time.sleep(5)
print("'I don't even know who *twitch* you are'")
time.sleep(5)
print("Stranger: 'okay, I am going to take your word for it. Since I have not seen anyone in the past four years.")
time.sleep(5)
print("Well, I guess I can start with my name, Emily.'")
time.sleep(5)
print("'" + str (name) + "'")
time.sleep(5)
print("Emily: 'Well, it all started with the poison that suddenly appeared and started to turn people into savages.")
time.sleep(5)
print("I was at home in my underground lab when it all happened, hiding from the police'")
time.sleep(5)
print("*twitch*'Why were you hiding from the police, they could have helped you?'")
time.sleep(5)
print("Emily: 'No they were going to going to arrest me for something I never did, ")
time.sleep(5)
print("Back in highschool Elon was my best friend and best programmer I have ever seen.")
time.sleep(5)
print("However, he was always envious that I discovered a cure that will make us live longer and stronger. ")
time.sleep(5)
print("The day I was going to present the ultimate medicine that was going to heal people's illnesses, all my stuff went missing,")
time.sleep(5)
print("and when I told people about it, they thought I was crazy. From that very moment, I was suspicious of my best friend Elon stealing all of my work.")
time.sleep(5)
print("So when he got rich with his programming intelligence,")
time.sleep(5)
print("he hired officers to look for me to put me and put me in jail because he accused me of trying to steal his life’s worth of work.")
time.sleep(5)
print("When he was the one who stole my life-changing work.'")
time.sleep(5)
print("Wow he really isn't the man we *twitch* all thought of then if you are saying the truth")
time.sleep(5)
print("Emily: 'ya'")
time.sleep(5)
print("*I look around*'Where are we?'")
time.sleep(5)
print("Emily: 'we are in a restaurant the safest place I can find'")
time.sleep(5)
print("'So like are you the only one living on Earth?'")
time.sleep(5)
print("Emily: 'yes, the only survivor from the poison that I know of.'")
time.sleep(5)
print("Anyways you are probably hungry, do you want a hamburger or a chicken sandwich?'")
time.sleep(5)

hungry = int(input("1= hamburger sandwich, 2= chicken sandwich, 3= sorry I am vegan, 4= no thanks I am not hungry"))
if hungry == 1:
    print("Emily:'hamburger sandwich it is.'")
    time.sleep(2)
    print("What toppings would you like on it")
    time.sleep(2)
    print("'Any *twitch* toppings?!'")
    time.sleep(2)
    print("Emily:'I mean yes, it is free, it is like an open Buffet of toppings'")
    time.sleep(4)
    print("'In that case I will have'")
    toppings = ["1:lettuce", "2:tomatoes", "3:onions", "4:olives", "5:cucumbers", "6:peppers"]
    counter = 0
    for i in toppings:
        counter += 1
        print (i)
        
    count = 0    
    a = True
    while a == True:
       insert = int(input())
       print (str (toppings [insert -1]))
       print ("anything else?")
       getmore = int(input("1:yes or 2:no"))
       if getmore == 1:
           count += 1
           if count >= 5:
               print("Emily: 'wow you seem hungry, but I don't think the sandwich can handle anymore toppings'")
               break
           else:
               continue 
       if getmore == 2:
           break
       else:
           break

elif hungry == 2:
    print("Emily:'chicken sandwich it is.'")
    time.sleep(2)
    print("What toppings would you like on it")
    time.sleep(2)
    print("'Any toppings?!'")
    time.sleep(2)
    print("Emily:'I mean yes, it is free, it is like an open Buffet of toppings'")
    time.sleep(3)
    print("'In that case I will have'")
    time.sleep(2)
    toppings = ["1:lettuce", "2:tomatoes", "3:onions", "4:olives", "5:cucumbers", "6:peppers"]
    counter = 0
    for i in toppings:
        counter += 1
        print (i)
        
    count = 0    
    a = True
    while a == True:
       insert = int(input())
       print (str (toppings [insert -1]))
       print ("anything else?")
       getmore = int(input("1:yes or 2:no"))
       if getmore == 1:
           count += 1
           if count >= 5:
               print("Emily: 'wow you seem hungry, but I don't think the sandwich can handle anymore toppings'")
               break
           else:
               continue 
       if getmore == 2:
           break
       else:
           break
        
elif hungry == 3:
    print("Emily: 'VEGAN! man I guess animals couldn't survive on Mars then?'")
    time.sleep(3)
    print("'No they can survive, I just prefer to be *twitch* vegan'")
    time.sleep(3)
    print("Emily: 'well do you want a shake then? because you need to have something to consume'")
    time.sleep(3)
    print("'sure'")
    time.sleep(3)

elif hungry == 4:
    print("*I start to feel dizzy and I then I suddenly woke up*'what happened?'*twitch*")
    time.sleep(4)
    print("Emily: 'What happened was that you were dehydrated and hungry,")
    time.sleep(4)
    print("so I put an IV to hydrate and give you the nutrients you need to be fully awake again'")
    time.sleep(4)
    print("However, you do need to eat this sandwich to get charged up, so")
    time.sleep(4)

else:
    print("Emily: 'sorry?'")
    time.sleep(2)
    print("*I start to feel dizzy and I then I suddenly woke up*'what happened?'*twitch*")
    time.sleep(3)
    print("Emily: 'What happened was that you were dehydrated and hungry,")
    time.sleep(4)
    print("so I put an IV to hydrate and give you the nutrients you need to be fully awake again'")
    time.sleep(4)
    print("However, you do need to eat this sandwich to get charged up, so")
    time.sleep(4)
    
print("here you go")
time.sleep(1)
print("so tell me about your self, other than the fact that you were forced to come down to Earth by your mother who is the president'")
time.sleep(4)
print("'wait how *twitch* did you know that'")
time.sleep(4)
print("Well when I took the chip from your brain and uploaded all your memories back to where they belong,")
time.sleep(4)
print("I kind of had to watch what some of your memories as they got uploaded to your brain")
time.sleep(4)
print("you are lucky that I am familiar with Elon's coding'")
time.sleep(4)
print("*it then hit me*'OH MY GOSH *twitch* Elon Musk is trying to kill humanity'")
time.sleep(4)
print("Emily:'What? How do you know that?'")
time.sleep(4)
print("'I don't...it is like a memory'")
time.sleep(4)
print("Emily:'Oh My that explains why you keep on twitching,")
time.sleep(4)
print("it is because your brain is going through a stressful time trying to handle all of the uploaded information all at the same time")
time.sleep(4)
print("well what else do you remember?'")
time.sleep(4)
print("'um... all I remember is something about killing humanity with a reverse formula'")
time.sleep(4)
print("Emily:'This explains everything, Elon Musk is the one who stole my formula that was supposed to save the world.")
time.sleep(4)
print("However, I also almost discovered a way that could ruin humanity for life, that doesn't make sense though why would he want to ruin mankind...")
time.sleep(4)
print("so he can pretend he saved humanity and get recognized  for his works and become rich forever.")
time.sleep(4)
print("Why would he then send you down here?'")
time.sleep(4)
print("'I remember he said we have to erase his memory *twitch* to concentrate on the objective'")
time.sleep(4)
print("Emily: 'but what would the objective be? Wait let me investigate the chip again...")
time.sleep(4)
print("there is a destination that was created, hold on that is Elon's house, well I guess I know where we are going.")
time.sleep(4)
print("Should we take the Bugatti or the Tesla?")
time.sleep(4)

car = int(input("1= Bugatti 2= Tesla Model Y"))
if car == 1:
    print("Well then lets go for a ride'")
    time.sleep(3)
    print("'wow we have so much freedom, can I drive'")
    time.sleep(3)
    print("Emily:'no'")
    time.sleep(3)
    print("'well not as much freedom as I thought'")
    time.sleep(3)
    print("Emily: 'just get in'")
    time.sleep(3)
    print("'okay fine jheez'")
    time.sleep(3)
    print("*we arrived to our destination* Emily: 'should we enter from the front of the house or the backyard?'")
    time.sleep(3)
    
    enter = (input("a = front b = backyard"))
    if enter == "a":
        print("Emily: 'I wanted to go from the backyard to feel like a spy, but okay I guess'")
        time.sleep(3)
        print("*Gaint drones appeared out of nowhere and started firing at us* 'Run for your lifetime!' ")
        time.sleep(3)
        print("*Emily holds my hand and drags me to a window that was near the door, she then cracks the corner of the window which smashed the entire window and quickly hop inside*")
        time.sleep(6)
        print("*Twitch*'That was a close one'")
        time.sleep(3)
        print("Emily: 'do you think we will have a better chance of finding the cure going to the backyard?'")
        time.sleep(3)
        choice = (input("aa= go to backyard bb= go to the kitchen instead"))
        if choice == "aa":
            print("'fine lets go to the backyard, I mean you know him best'")
            
        elif choice == "bb":
            print("'nah I think he has a undercover lab somehow in the kitchen'")
            time.sleep(3)
            print("*we go to the kitchen and find a stick note as a reminder for Elon that his lab is not in the Kitchen but in the back yard*'Your lab is in the backyard'")
            time.sleep(6)
            print("'well I guess you know him best. Backyard it is'")
            time.sleep(3)
            
        else:
            print("Emily: 'you really think it somewhere else, nonono you have to trust me on this, it is probably in the backyard'")
            
    elif enter == "b":
        print("Emily: 'lets get it'")
        
    else:
        print("Emily: 'dude just pick from the options. No you know what we are going to the backyard'")
        
    

elif car == 2:
    print("Dang, I wanted to drive the Bugatti'")
    time.sleep(3)
    print("Can I drive then")
    time.sleep(3)
    print("Emily: 'absolutely not'")
    time.sleep(3)
    print("'so much for the freedom we have'")
    time.sleep(3)
    print("*we start heading to Elon's house, and suddenly we start hearing beeping noises* beep beep beep 'what is happening?'*the beeping got faster and faster*")
    time.sleep(3)
    print("Emily:'get out of the car'")
    time.sleep(3)
    print("NOW!'")
    time.sleep(3)
    print("*We both jump out as an explosion occurred and luckily we were safe*")
    time.sleep(3)
    print("Emily: 'Elon is unto us, I mean it is his car for crying out loud, how can we be so dumb to use it.")
    time.sleep(3)
    print("well on the bright side we have the Bugatti that I wanted to drive from the beginning, and the bad news is that we probably have very little time left.")
    time.sleep(7)
    print("before Elon sets another bomb and we disintegrate into dust.'")
    time.sleep(3)
    print("*we arrived at our destination* Emily: 'should we enter from the front of the house or the backyard?'")
    time.sleep(3)
    
    enter = (input("a = front b = backyard"))
    if enter == "a":
        print("Emily: 'I wanted to go from the backyard to feel like a spy, but okay I guess'")
        time.sleep(3)
        print("*Gaint drones appeared out of nowhere and started firing at us* 'Run for your lifetime!' ")
        time.sleep(3)
        print("*Emily holds my hand and drags me to a window that was near the door, she then cracks the corner of the window which smashed the entire window and quickly hop inside*")
        time.sleep(7)
        print("*Twitch*'That was a close one'")
        time.sleep(3)
        print("Emily: 'do you think we will have a better chance of finding the cure going to the backyard?'")
        choice = (input("aa= go to backyard bb= find protection first then go to the backyard"))
        if choice == "aa":
            print("'fine lets go to the backyard, I mean you know him best'")
            
        elif choice == "bb":
            print("'nah I think we need to get suited up first so if any other flying machine guns come at us, we are atleast prepared'")
            time.sleep(5)
            print("*we looked around the house and all we could find is pillows to put around our bodies and a grabage bin cover to protect us")
            time.sleep(5)
            print("we looked like kids who are going to fihgt an imagineary dragon*")
            time.sleep(4)
            print("'Now we are ready to go to the backyard'")
            time.sleep(3)
            
        else:
            print("Emily: 'Oh you know what I don't trust you anymore picking anything, so we will go to the backyard'")
            
    elif enter == "b":
        print("Emily: 'Alright, lets go quickly'")
        
    else:
        print("Emily: 'dude just pick from the options. No you know what we are going to the backyard'")

    
else:
    print("Emily: 'These are the only two cars I have for now.")
    time.sleep(3)
    print("You know what maybe I should pick since I am the adult'")
    time.sleep(3)
    print("*we then headed to the Tesla and all of the sudden it exploded, and flying machine guns chased us down*Emily:'Oh no. Run this way to Elon's house.")
    time.sleep(6)
    print("*When we said this the drones stopped chasing us* Oh Thank God'")
    time.sleep(3)
    print("*we then quickly hopped into the Bugatti and drove to Elon's house*Emily: 'Let's break-in from the backyard'")
    time.sleep(3)

print("*we went to the backyard and all we found was a hut in the middle of the backyard.")
time.sleep(5)
print("Curiously enough we opened it and we found an elevator that goes down 5 floors*'well that was convenient.'")
time.sleep(5)
print("Emily: 'As smart as Elon is, he is not very intelligent when it comes placing objects'")
time.sleep(5)
print("*we arrive at the fifth floor down, and the security alarm starts beeping*")
time.sleep(5)
print("*ten seconds later we hear a voice from the walls* stranger: 'Emily, is that you?!'")
time.sleep(5)
print("Emily: 'E-E-Elon?'")
time.sleep(5)
print("Elon; 'Look Emily I missed up, maybe we can discuss this for lunch or something?'")
time.sleep(5)
print("Emily: 'Ya right Elon, not after *meanwhile they were arguing, I was looking for the cure* you stole my life, betrayed me, and broke my heart'")
time.sleep(5)
print("'wait you guys were a thing?'")
time.sleep(5)
print("Emily: 'Not now " + str(name) + "!'")
time.sleep(5)
print("'wow okay okay' *seconds later* 'is this it?'")
time.sleep(5)
print("Emily: 'Quick! pick one so we can launch it in this device'")
time.sleep(5)
print("'How do you know, what this device can do?'")
time.sleep(5)
print("Emily: 'because I created it, it will trigger rockets around the world that will explode in the air, and cure every living thing. Now pick one Humanity depends on it'")
time.sleep(5)
print("'what do you mean pick one?!'")
time.sleep(3)
print("'um...'")
time.sleep(3)
print("'uh...'")
time.sleep(3)
print("*I suddenly remember a verse form the Bible that my mom used to tell me about all the time. 'Enter through the narrow gate.")
time.sleep(3)
print("For wide is the gate and broad is the road that leads to destruction, and many enter through it.")
time.sleep(3)
print("But small is the gate and narrow the road that leads to life, and only a few find it' Matthew 7:13-14.")
time.sleep(3)
print("I did the sign of the cross and hoped God would be with me right now.*")
time.sleep(3)
print("'...'")
time.sleep(3)
print("*sweat starts dripping down my face. but then I pick one*")
time.sleep(3)

substance = (input("r= bright red, d= dark green, g= There is no way this could be the only solution"))
if substance == "r":
    print("*I grabbed the bright red*'Here you go'")
    time.sleep(3)
    print("*Emily inserts the substance in the device* Emily: 'Press the red button'" + str(name) + "!")
    time.sleep(3)
    print("*I pressed the red button*")
    time.sleep(3)
    print("Elon: 'You fools. HAHAHAHA. The button is for self destruction. I made it just incase you came along and tried to ruin my plan.HAHAHA.'")
    time.sleep(3)
    print("*the lab suddendly went into lock down, metal walls started to seal the lab, so we have no where to go. A counter on the T.V. showed up for 10 seconds*")
    time.sleep(6)
    slowfastprint("10 9 8 7")
    print("*I hear a voice from far*")
    time.sleep(3)
    slowfastprint("6 5 4")
    print("*a very fimilar voice starts to talk*")
    time.sleep(3)
    slowfastprint("3")
    print("stranger: 'arrest him!'*could that be my mom*")
    time.sleep(3)
    slowfastprint("2")
    print("*all I heard was typing on a keyboard as me and Emily were scared to death*")
    time.sleep(4)
    slowfastprint("1")
    time.sleep(2)
    print("computer: 'self destruct cancelled'*metal wall slowly went up as I was comforted*")
    time.sleep(4)
    print("Mom: '" + str(name) + "?'")
    time.sleep(3)
    print("'mom? I am so happy to hear your voice.'")
    time.sleep(3)
    print("Mom: 'Don't worry everything is under control, we discovered what Elon was trying to do, and if it wasn't for you and Emily humanity wouldn't have been saved.")
    time.sleep(7)
    print("As long as you have can recreate the cure that to save mankind Emily")
    time.sleep(3)
    print("Emily: 'Yes ma'am, I have all my studies and resources now'")
    time.sleep(3)
      
elif substance == "d":
    print("*I grabbed the dark green substance*'Here you go'")
    time.sleep(3)
    print("*Emily inserts the substance in the device* Emily: 'Press the red button'" + str(name) + "!")
    time.sleep(3)
    print("*I pressed the red button*")
    time.sleep(3)
    print("Elon: 'You fools. HAHAHAHA. The button is for self destruction. I made it just incase you came along and tried to ruin my plan.HAHAHA.'")
    time.sleep(3)
    print("*the lab suddendly went into lock down, metal walls started to seal the lab, so we have no where to go. A counter on the T.V. showed up for 10 seconds*")
    time.sleep(3)
    slowfastprint("10 9 8 7")
    print("*I hear a voice from far*")
    time.sleep(2)
    slowfastprint("6 5 4")
    print("*a very fimilar voice starts to talk*")
    time.sleep(3)
    slowfastprint("3")
    print("stranger: 'arrest him!'*could that be my mom*")
    time.sleep(3)
    slowfastprint("2")
    print("*all I heard was typing on a keyboard as me and Emily were scared to death*")
    time.sleep(3)
    slowfastprint("1")
    print("computer: 'self destruct cancelled'*metal wall slowly went up as I was comforted*")
    time.sleep(3)
    print("Mom: '" + str(name) + "?'")
    time.sleep(3)
    print("'mom? I am so happy to hear your voice.'")
    time.sleep(3)
    print("Mom: 'Don't worry everything is under control, we discovered what Elon was trying to do, and if it wasn't for you and Emily humanity wouldn't have been saved.")
    time.sleep(3)
    print("As long as you have can recreate the cure that to save mankind Emily")
    time.sleep(3)
    print("Emily: 'Yes ma'am, I have all my studies and resources now'")
    time.sleep(3)
    
elif substance == "g":
    print("'No, I this can't be the cure'")
    time.sleep(3)
    print("*I hear a voice from far*")
    time.sleep(3)
    print("*a very fimilar voice starts to talk*")
    time.sleep(3)
    print("stranger: 'arrest him!'*could that be my mom*")
    time.sleep(3)
    print("Mom: '" + str(name) + "?'")
    time.sleep(3)
    print("'mom? I am so happy to hear your voice.'")
    time.sleep(3)
    print("Mom: 'Don't worry everything is under control, we discovered what Elon was trying to do, and if it wasn't for you and Emily humanity wouldn't have been saved.")
    time.sleep(3)
    print("As long as you have can recreate the cure that to save mankind Emily")
    time.sleep(3)
    print("Emily: 'Yes ma'am, I have all my studies and resources now'")
    time.sleep(3)
    
else:
    print("'no'")
    time.sleep(3)
    print("Emily: 'fine I guess I will do it then'*Emily inserts the substance in the device*")
    time.sleep(3)
    print("*EMily pressed the red button*")
    time.sleep(3)
    print("Elon: 'You fools. HAHAHAHA. The button is for self destruction. I made it just incase you came along and tried to ruin my plan.HAHAHA.'")
    time.sleep(3)
    print("*the lab suddendly went into lock down, metal walls started to seal the lab, so we have no where to go. A counter on the T.V. showed up for 10 seconds*")
    time.sleep(5)
    slowfastprint("10 9 8 7")
    print("*I hear a voice from far*")
    time.sleep(3)
    slowfastprint("6 5 4")
    print("*a very fimilar voice starts to talk*")
    time.sleep(3)
    slowfastprint("3")
    print("stranger: 'arrest him!'*could that be my mom*")
    time.sleep(3)
    slowfastprint("2")
    print("*all I heard was typing on a keyboard as me and Emily were scared to death*")
    time.sleep(3)
    slowfastprint("1")
    print("computer: 'self destruct cancelled'*metal wall slowly went up as I was comforted*")
    time.sleep(3)
    print("Mom: '" + str(name) + "?'")
    time.sleep(3)
    print("'mom? I am so happy to hear your voice.'")
    time.sleep(3)
    print("Mom: 'Don't worry everything is under control, we discovered what Elon was trying to do, and if it wasn't for you and Emily humanity wouldn't have been saved.")
    time.sleep(3)
    print("As long as you have can recreate the cure that to save mankind Emily")
    time.sleep(7)
    print("Emily: 'Yes ma'am, I have all my studies and resources now'")
    time.sleep(3)

print("*beeping starts to occur again*' mom is everything okay?'")
print("Mom: 'uh no it seem to ask for a password?'")
print("Emily: 'oh I reset the password, but I don't remember what it was." + str(name) + " do you remember it?")
print("'is there a hint given?'")
print("Mom: 'yes hint is " + str(hint))
number = 0
password2 = (input("I get one chance and one chance only it is "))
while password1 == password2:
    print("*Wow God is amazing* 'Thank you God!'")
    break
else:
    slowfastprint("10 9 8 7 6 5 4 3 2 1")
    print("computer: 'Humanity is destoryed'")


